[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.126.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.126.0"

[context.deploy-preview]
  command = "hugo --gc --minify --buildDrafts --buildFuture"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.126.0"

[context.branch-deploy]
  command = "hugo --gc --minify"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.83.1"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
